export default {
  GET_NEXT_PLAYER: 'players/START_PLAYER_TURN',
  SET_CURRENT_PLAYER: 'players/SET_CURRENT_PLAYER',
  SET_PLAYER: 'players/SET_PLAYER',
  PLAYER_IS_BOT: 'players/PLAYER_IS_BOT',
  PLAYER_IS_HUMAN: 'players/PLAYER_IS_HUMAN'
};
